name: Spec Intake (issues → capsule comment)
on:
  issues:
    types: [opened, edited, labeled]

permissions:
  issues: write

jobs:
  comment:
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'spec-draft') ||
      (github.event.action != 'labeled' && contains(github.event.issue.labels.*.name, 'spec-draft'))
    runs-on: ubuntu-latest
    steps:
      - name: Dump event (debug)
        run: |
          echo "EVENT=${GITHUB_EVENT_NAME}"
          jq . < "$GITHUB_EVENT_PATH" || true
      
      - name: Post capsule ack
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BODY="📌 Spec received. /cc @${{ secrets.CLAUDE_HANDLE || 'ClaudeCode' }}"
          jq -Rs --arg b "$BODY" '{"body":$b}' <<<"" > body.json
          curl -sS -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
            -d @body.json \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
